/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        ArrayList<String> lista = new ArrayList<>();
        ArrayList<Pessoa> pessoas = new ArrayList<>();

        lista.add("POO");
        lista.add("FEI");
        lista.add("EST");
        lista.add("FDM");
        Pessoa pessoa = new Pessoa("Mario", "armario_mario1@gmail.com");
        pessoas.add(pessoa);
        pessoas.add(new Pessoa("Luigi", "armarioVerde1@gmail.com"));
        pessoas.add(new Pessoa("Francesco", "chiquitoLinguicito@gmail.com"));
        pessoas.add(new Pessoa("Pessego", "pricesaDosArmarios@gmail.com"));

        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i));
        }

        //ForEach
        for (String elemento : lista) {
            System.out.println(elemento);
        }
        
        //Expressão lambda
        lista.forEach(elemento-> System.out.println(elemento) );

        //Method reference
        lista.forEach(System.out::println);

        lista.removeIf(elemento-> elemento.equals("POO"));

        lista.forEach(System.out::println);

        for (Pessoa p : pessoas) {
            System.out.println(p.toString());
        }

        pessoas.forEach(System.out::println);

        pessoas.removeIf(elemento->elemento.getNome().equals("Mario"));

        pessoas.forEach(System.out::println);

        Pessoa pe = pessoas.stream()
        .filter(elemento->elemento.getNome().equals("Luigi"))
        .findFirst()
        .orElse(null);

        //Talvez dispare exceção. Melhor fazer um if para garantir
        //que pe não é referência para null
        if(pe != null) {
            String n = pe.getNome();
            System.out.println(n);
        }
    
    }
}