/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Caixa<String> c = new Caixa<>();
        String s = "Olá mundo";
        c.set(s);
        String outra = c.getDado();
        System.out.println(outra);
    }
}
