/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Aviao aviao = new Aviao(5, 50, 500,
                1000, 2, "Turbina" );
        aviao.ligaDesligaAviao();
        System.out.println(aviao.toString());
    }
}
