/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Telefone t = new Telefone(1, "1a2b", "ultraMaster2000",
                2, new Dimensao(20, 40, 10) );
        System.out.println(t.imprimirDados());
        Semfio st = new Semfio(2, "3c4d", "ultraMaster2001", 3,
                new Dimensao(10, 50, 15), 2, 90, 200);
        System.out.println(st.imprimirDados());
    }
}
