/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {

    public static void main(String[] args) {
        Pilha<String> p = new Pilha<>(5);
//        System.out.println(p.isCheia());
//        System.out.println(p.isVazia());
        p.empilhar("Jorge");
        System.out.println(p.desempilhar());
//        System.out.println(p.desempilhar());
    }
}
