/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {


    public static void main(String[] args) {


//        Disciplina d = new Disciplina("POO", new DiasDaSemana[]
//                {DiasDaSemana.SEGUNDA, DiasDaSemana.QUINTA}
//        );
//        System.out.println(d);
//
//        for (DiasDaSemana a : DiasDaSemana.values()) {
//            System.out.println(a);
//        }
//        DiasDaSemana e = DiasDaSemana.SEGUNDA;
//        switch (e) {
//            case SEGUNDA -> System.out.println("Tem aula");
//            case TERCA -> System.out.println("Não tem aula");
//            case QUARTA -> System.out.println("Não tem aula");
//            case QUINTA -> System.out.println("Tem aula");
//        }
//
//        for(Planetas p: Planetas.values()){
//            System.out.println(p);
//        }

//        Carta tresDePaus = new Carta(Naipes.ESPADAS, Valores.REI);
//        System.out.println(tresDePaus);

        List<Carta> baralho = new ArrayList<>();
        for (Naipes n: Naipes.values() ) {
            for(Valores v: Valores.values()) {
                baralho.add(new Carta(n, v));
            }
        }


        Collections.shuffle(baralho);
        for (Carta c: baralho) {
            System.out.println(c.toString() + " ");
        }
    }
}

