/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

import java.util.Random;

public class App implements DrawListener {
    private Draw draw;

    public App () {
        this.draw = new Draw();
        this.draw.addListener(this);
        this.draw.show();
    }


    @Override
    public void mousePressed(double x, double y) {
        Random r = new Random();
        double d = r.nextDouble(.01, .1);
        Bandeira b = new Bandeira(new double[] {x, y}, d);
        b.desenhar(draw);
    }

    @Override
    public void keyTyped(char c) {
        if(c == 'c') {
            this.draw.clear();
        }
    }

    public static void main(String[] args) {
        App app = new App();
//        draw.setPenColor(0, 0, 0);
//        draw.rectangle(.5, .5, .3, .2);
//        draw.setPenColor(255,0,0);
//        draw.filledCircle(0.5, 0.5, 0.1);
//        Bandeira b = new Bandeira(new double[] {.5, .5}, 0.1);
//        Bandeira c = new Bandeira(new double[] {.8, .8}, 0.05);
//        Bandeira d = new Bandeira(new double[] {.2, .3}, 0.02);
//        b.desenhar(draw);
//        c.desenhar(draw);
//        d.desenhar(draw);
    }
}
