/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public static void main(String[] args) {
        Contador contador = new Contador();

        contador.definirValorAtual(-1);
        System.out.println(contador.obterValorAtual());
        contador.incrementaUm();
        System.out.println(contador.obterValorAtual());
    }
}
